Repository tuannqhe151337/fin-planning-backend, pull requests merged in 2024-08, with the labels that each got.

#209 [feature] report detail v2
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/responses/report/detail/ReportDetailResponse.java
  src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
  src/main/java/com/example/capstone_project/repository/result/ReportDetailResult.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/mapper/report/detail/ReportDetailMapper.java
Labels: enhancement, task

#210 [feature] calculate actual cost and expected cost
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/responses/report/calculate/ReportActualCostResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/calculate/ReportExpectedCostResponse.java
  src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
Labels: task

#216 [feature] add get all list cost type
  src/main/java/com/example/capstone_project/controller/CostTypeController.java
  src/main/java/com/example/capstone_project/service/CostTypeService.java
  src/main/java/com/example/capstone_project/service/impl/CostTypeServiceImpl.java
Labels: enhancement

#217 [feature] add get all department
  src/main/java/com/example/capstone_project/controller/DepartmentController.java
  src/main/java/com/example/capstone_project/service/DepartmentService.java
  src/main/java/com/example/capstone_project/service/impl/DepartmentServiceImpl.java
Labels: enhancement

#212 [feature] term list when create new plan feature
  src/main/java/com/example/capstone_project/controller/TermController.java
  src/main/java/com/example/capstone_project/repository/impl/TermRepositoryImpl.java
  src/main/java/com/example/capstone_project/service/impl/TermServiceImpl.java
Labels: enhancement, task

#215 [feature] update feature plan reupload v2
  src/main/java/com/example/capstone_project/repository/TermRepository.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
Labels: enhancement, task

#201 [feature] report download v2
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/entity/CostType.java
  src/main/java/com/example/capstone_project/entity/Position.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/result/ExpenseResult.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/helper/HandleFileHelper.java
Labels: task

#203 create term + schedule term
  src/main/java/com/example/capstone_project/service/impl/UserServiceImpl.java
  src/test/java/term/TermScheduleTest.java
  src/test/java/term/TermServiceTest.java
  src/test/java/user/UserServiceTest.java
Labels: enhancement, test, feature

#225 [feature] fix plan download each version, last version and template
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanRepository.java
  src/main/java/com/example/capstone_project/repository/result/ExpenseResult.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/helper/HandleFileHelper.java
  src/main/resources/fileTemplate/Financial Planning_AnnualReport_v1.0.xls
  src/main/resources/fileTemplate/Financial Planning_AnnualReport_v1.0.xlsx
  src/main/resources/fileTemplate/Financial Planning_v1.0.xls
  src/main/resources/fileTemplate/Financial Planning_v1.0.xlsx
Labels: enhancement, task

#240 [feature] report approval expenses
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/body/expense/ApprovalAllExpenseBody.java
  src/main/java/com/example/capstone_project/controller/body/expense/ApprovalExpenseBody.java
  src/main/java/com/example/capstone_project/controller/body/expense/DenyExpenseBody.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
  src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
  src/main/java/com/example/capstone_project/repository/result/ReportExpenseResult.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/enums/ReportStatusCode.java
  src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java
  src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java
Labels: enhancement

#243 [feature] report approval expenses
  src/main/java/com/example/capstone_project/repository/ExpenseStatusRepository.java
  src/main/java/com/example/capstone_project/repository/ReportStatusRepository.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
Labels: enhancement

#265 [feature] fix not return re-upload plan when re-upload successful
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/reupload/ReUploadExpensesMapper.java
Labels: bug

#266 [feature] report upload
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/body/expense/ExpenseBody.java
  src/main/java/com/example/capstone_project/controller/body/expense/UploadReportExpenses.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java
Labels: enhancement, task

#267 Fix authority for feature
  src/main/java/com/example/capstone_project/controller/AnnualReportController.java
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/impl/AnnualReportServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
Labels: enhancement

#283 [feature] add filter by projectId, supplierId, picId for plan expenses
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/repository/CustomFinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/expenses/PlanExpenseResponseMapper.java
Labels: enhancement

#284 [feature] add filter by projectId, supplierId, picId for report expenses
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/responses/report/PicResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/ProjectResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/SupplierResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/expenses/ExpenseResponse.java
  src/main/java/com/example/capstone_project/repository/CustomFinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java
Labels: enhancement, backend

#288 [feature] download and upload
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/controller/body/plan/reupload/ReUploadExpenseBody.java
  src/main/java/com/example/capstone_project/repository/ExpenseStatusRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanFileRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanRepository.java
  src/main/java/com/example/capstone_project/repository/result/ExpenseResult.java
  src/main/java/com/example/capstone_project/repository/result/FileNameResult.java
  src/main/java/com/example/capstone_project/repository/result/UserDownloadResult.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/helper/HandleFileHelper.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/create/CreatePlanMapper.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/reupload/ReUploadExpensesMapper.java
  src/main/resources/fileTemplate/Financial Planning_v1.0.xls
  src/main/resources/fileTemplate/Financial Planning_v1.0.xlsx
Labels: enhancement, backend

#289 [feature] add expense code to response
  src/main/java/com/example/capstone_project/controller/responses/report/expenses/ExpenseResponse.java
  src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
  src/main/java/com/example/capstone_project/repository/result/ReportExpenseResult.java
  src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java
Labels: enhancement

#295 [feature] add expense code to plan expense
  src/main/java/com/example/capstone_project/controller/responses/expense/list/ExpenseResponse.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/expenses/PlanExpenseResponseMapper.java
Labels: enhancement

#294 [feature] exchange rate and crruncy CRUD
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/CurrencyController.java
  src/main/java/com/example/capstone_project/controller/CurrencyExchangeRateController.java
  src/main/java/com/example/capstone_project/controller/body/currency/DeleteCurrencyBody.java
  src/main/java/com/example/capstone_project/controller/body/currency/NewCurrencyBody.java
  src/main/java/com/example/capstone_project/controller/body/currency/UpdateCurrencyBody.java
  src/main/java/com/example/capstone_project/controller/body/exchange/CreateExchangeBody.java
  src/main/java/com/example/capstone_project/controller/body/exchange/DeleteExchangeBody.java
  src/main/java/com/example/capstone_project/controller/body/exchange/ExchangeBody.java
  src/main/java/com/example/capstone_project/controller/body/exchange/UpdateExchangeBody.java
  src/main/java/com/example/capstone_project/controller/responses/currency/CurrencyPaginateResponse.java
  src/main/java/com/example/capstone_project/controller/responses/exchange/CurrencyResponse.java
  src/main/java/com/example/capstone_project/controller/responses/exchange/ExchangeRateResponse.java
  src/main/java/com/example/capstone_project/controller/responses/exchange/MonthExchangeRateResponse.java
  src/main/java/com/example/capstone_project/entity/Currency.java
  src/main/java/com/example/capstone_project/entity/CurrencyExchangeRate.java
  src/main/java/com/example/capstone_project/repository/CurrencyExchangeRateRepository.java
  src/main/java/com/example/capstone_project/repository/CurrencyRepository.java
  src/main/java/com/example/capstone_project/repository/CustomCurrencyExchangeRateRepository.java
  src/main/java/com/example/capstone_project/repository/CustomCurrencyRepository.java
  src/main/java/com/example/capstone_project/repository/impl/CurrencyExchangeRateRepositoryImpl.java
  src/main/java/com/example/capstone_project/repository/impl/CurrencyRepositoryImpl.java
  src/main/java/com/example/capstone_project/repository/result/PaginateExchange.java
  src/main/java/com/example/capstone_project/service/CurrencyExchangeRateService.java
  src/main/java/com/example/capstone_project/service/CurrencyService.java
  src/main/java/com/example/capstone_project/service/impl/CurrencyExchangeRateServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/CurrencyServiceImpl.java
  src/main/java/com/example/capstone_project/service/result/ExchangeResult.java
  src/main/java/com/example/capstone_project/utils/enums/Affix.java
  src/main/java/com/example/capstone_project/utils/enums/AuthorityCode.java
Labels: enhancement, backend

#296 [feature] report approval v2
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/body/expense/ExpenseBody.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanExpenseRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/helper/RemoveDuplicateHelper.java
Labels: enhancement

#299 [feature] exchange money for plan expense and report expense
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/responses/expense/CurrencyResponse.java
  src/main/java/com/example/capstone_project/controller/responses/expense/list/ExpenseResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/expenses/ExpenseResponse.java
  src/main/java/com/example/capstone_project/entity/Currency.java
  src/main/java/com/example/capstone_project/entity/FinancialPlanExpense.java
  src/main/java/com/example/capstone_project/repository/CurrencyRepository.java
  src/main/java/com/example/capstone_project/repository/impl/FinancialPlanExpenseRepositoryImpl.java
  src/main/java/com/example/capstone_project/repository/result/ExchangeRateResult.java
  src/main/java/com/example/capstone_project/repository/result/ReportExpenseResult.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/expenses/PlanExpenseResponseMapper.java
  src/main/java/com/example/capstone_project/utils/mapper/report/expenses/ReportExpenseResponseMapper.java
Labels: enhancement, backend

#301 [feature] upload and reupload plan
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/controller/body/plan/create/ExpenseBody.java
  src/main/java/com/example/capstone_project/controller/body/plan/reupload/ReUploadExpenseBody.java
  src/main/java/com/example/capstone_project/controller/responses/plan/UserResponse.java
  src/main/java/com/example/capstone_project/repository/UserRepository.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/create/CreatePlanMapper.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/reupload/ReUploadExpensesMapper.java
Labels: enhancement, backend

#300 [feature] download feature
  src/main/java/com/example/capstone_project/repository/FinancialPlanRepository.java
  src/main/java/com/example/capstone_project/repository/result/ExpenseResult.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/utils/helper/HandleFileHelper.java
  src/main/resources/fileTemplate/Financial Planning_v1.0.xls
  src/main/resources/fileTemplate/Financial Planning_v1.0.xlsx
Labels: enhancement, backend

#306 [feature] actual cost and expected cost
  src/main/java/com/example/capstone_project/config/SeedConfiguration.java
  src/main/java/com/example/capstone_project/controller/FinancialPlanController.java
  src/main/java/com/example/capstone_project/controller/ReportController.java
  src/main/java/com/example/capstone_project/controller/responses/plan/CurrencyResponse.java
  src/main/java/com/example/capstone_project/controller/responses/plan/detail/CostResponse.java
  src/main/java/com/example/capstone_project/controller/responses/plan/detail/PlanDetailResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/CurrencyResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/calculate/ReportActualCostResponse.java
  src/main/java/com/example/capstone_project/controller/responses/report/calculate/ReportExpectedCostResponse.java
  src/main/java/com/example/capstone_project/repository/CurrencyRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialPlanRepository.java
  src/main/java/com/example/capstone_project/repository/FinancialReportRepository.java
  src/main/java/com/example/capstone_project/repository/result/PaginateExchange.java
  src/main/java/com/example/capstone_project/repository/result/PlanDetailResult.java
  src/main/java/com/example/capstone_project/service/FinancialPlanService.java
  src/main/java/com/example/capstone_project/service/FinancialReportService.java
  src/main/java/com/example/capstone_project/service/impl/FinancialPlanServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/FinancialReportServiceImpl.java
  src/main/java/com/example/capstone_project/service/result/CostResult.java
  src/main/java/com/example/capstone_project/service/result/TotalCostByCurrencyResult.java
  src/main/java/com/example/capstone_project/utils/mapper/plan/detail/PlanDetailMapper.java
Labels: enhancement

#270 [feature] auto generate annual report v2
  src/main/java/com/example/capstone_project/entity/ReportStatistical.java
  src/main/java/com/example/capstone_project/repository/AnnualReportRepository.java
  src/main/java/com/example/capstone_project/repository/ReportRepository.java
  src/main/java/com/example/capstone_project/repository/ReportStatisticalRepository.java
  src/main/java/com/example/capstone_project/repository/TermStatusRepository.java
  src/main/java/com/example/capstone_project/repository/result/AnnualReportResult.java
  src/main/java/com/example/capstone_project/repository/result/CostStatisticalByCurrencyResult.java
  src/main/java/com/example/capstone_project/service/GenerateAnnualReportService.java
  src/main/java/com/example/capstone_project/service/TermService.java
  src/main/java/com/example/capstone_project/service/impl/GenerateAnnualReportServiceImpl.java
  src/main/java/com/example/capstone_project/service/impl/TermServiceImpl.java
  src/main/java/com/example/capstone_project/service/scheduler/TermSchedulerService.java
  src/main/java/com/example/capstone_project/utils/mapper/annual/AnnualReportMapper.java
Labels: enhancement
